// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loginLogFieldNames          = builder.RawFieldNames(&LoginLog{})
	loginLogRows                = strings.Join(loginLogFieldNames, ",")
	loginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(loginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(loginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLoginLogIdPrefix = "cache:loginLog:id:"
)

type (
	loginLogModel interface {
		Insert(ctx context.Context, data *LoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LoginLog, error)
		Update(ctx context.Context, data *LoginLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLoginLogModel struct {
		sqlc.CachedConn
		table string
	}

	LoginLog struct {
		Id         int64          `db:"id"`          // 日志ID
		UserId     sql.NullInt64  `db:"user_id"`     // 用户ID
		Username   string         `db:"username"`    // 用户名
		Ip         sql.NullString `db:"ip"`          // IP地址
		UserAgent  sql.NullString `db:"user_agent"`  // 浏览器UA
		Status     int64          `db:"status"`      // 状态: 0=失败 1=成功
		Remark     sql.NullString `db:"remark"`      // 备注(失败原因等)
		CreateTime time.Time      `db:"create_time"` // 创建时间
	}
)

func newLoginLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLoginLogModel {
	return &defaultLoginLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`login_log`",
	}
}

func (m *defaultLoginLogModel) Delete(ctx context.Context, id int64) error {
	loginLogIdKey := fmt.Sprintf("%s%v", cacheLoginLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, loginLogIdKey)
	return err
}

func (m *defaultLoginLogModel) FindOne(ctx context.Context, id int64) (*LoginLog, error) {
	loginLogIdKey := fmt.Sprintf("%s%v", cacheLoginLogIdPrefix, id)
	var resp LoginLog
	err := m.QueryRowCtx(ctx, &resp, loginLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginLogModel) Insert(ctx context.Context, data *LoginLog) (sql.Result, error) {
	loginLogIdKey := fmt.Sprintf("%s%v", cacheLoginLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, loginLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Ip, data.UserAgent, data.Status, data.Remark)
	}, loginLogIdKey)
	return ret, err
}

func (m *defaultLoginLogModel) Update(ctx context.Context, data *LoginLog) error {
	loginLogIdKey := fmt.Sprintf("%s%v", cacheLoginLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Ip, data.UserAgent, data.Status, data.Remark, data.Id)
	}, loginLogIdKey)
	return err
}

func (m *defaultLoginLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLoginLogIdPrefix, primary)
}

func (m *defaultLoginLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLoginLogModel) tableName() string {
	return m.table
}
