// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	operationLogFieldNames          = builder.RawFieldNames(&OperationLog{})
	operationLogRows                = strings.Join(operationLogFieldNames, ",")
	operationLogRowsExpectAutoSet   = strings.Join(stringx.Remove(operationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	operationLogRowsWithPlaceHolder = strings.Join(stringx.Remove(operationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOperationLogIdPrefix = "cache:operationLog:id:"
)

type (
	operationLogModel interface {
		Insert(ctx context.Context, data *OperationLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OperationLog, error)
		Update(ctx context.Context, data *OperationLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOperationLogModel struct {
		sqlc.CachedConn
		table string
	}

	OperationLog struct {
		Id         int64          `db:"id"`          // 日志ID
		UserId     int64          `db:"user_id"`     // 操作用户ID
		Username   string         `db:"username"`    // 操作用户名
		Action     string         `db:"action"`      // 操作类型
		TargetType sql.NullString `db:"target_type"` // 操作对象类型(user/task/category/config)
		TargetId   sql.NullInt64  `db:"target_id"`   // 操作对象ID
		Detail     sql.NullString `db:"detail"`      // 操作详情
		Ip         sql.NullString `db:"ip"`          // IP地址
		CreateTime time.Time      `db:"create_time"` // 创建时间
	}
)

func newOperationLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOperationLogModel {
	return &defaultOperationLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`operation_log`",
	}
}

func (m *defaultOperationLogModel) Delete(ctx context.Context, id int64) error {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, operationLogIdKey)
	return err
}

func (m *defaultOperationLogModel) FindOne(ctx context.Context, id int64) (*OperationLog, error) {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, id)
	var resp OperationLog
	err := m.QueryRowCtx(ctx, &resp, operationLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", operationLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOperationLogModel) Insert(ctx context.Context, data *OperationLog) (sql.Result, error) {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, operationLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Action, data.TargetType, data.TargetId, data.Detail, data.Ip)
	}, operationLogIdKey)
	return ret, err
}

func (m *defaultOperationLogModel) Update(ctx context.Context, data *OperationLog) error {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, operationLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Action, data.TargetType, data.TargetId, data.Detail, data.Ip, data.Id)
	}, operationLogIdKey)
	return err
}

func (m *defaultOperationLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, primary)
}

func (m *defaultOperationLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", operationLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOperationLogModel) tableName() string {
	return m.table
}
