// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemConfigFieldNames          = builder.RawFieldNames(&SystemConfig{})
	systemConfigRows                = strings.Join(systemConfigFieldNames, ",")
	systemConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(systemConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	systemConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(systemConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSystemConfigIdPrefix        = "cache:systemConfig:id:"
	cacheSystemConfigConfigKeyPrefix = "cache:systemConfig:configKey:"
)

type (
	systemConfigModel interface {
		Insert(ctx context.Context, data *SystemConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SystemConfig, error)
		FindOneByConfigKey(ctx context.Context, configKey string) (*SystemConfig, error)
		Update(ctx context.Context, data *SystemConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSystemConfigModel struct {
		sqlc.CachedConn
		table string
	}

	SystemConfig struct {
		Id          int64          `db:"id"`           // 配置ID
		ConfigKey   string         `db:"config_key"`   // 配置键
		ConfigValue string         `db:"config_value"` // 配置值
		Remark      sql.NullString `db:"remark"`       // 备注说明
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
		UpdateTime  time.Time      `db:"update_time"`  // 更新时间
	}
)

func newSystemConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSystemConfigModel {
	return &defaultSystemConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`system_config`",
	}
}

func (m *defaultSystemConfigModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	systemConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheSystemConfigConfigKeyPrefix, data.ConfigKey)
	systemConfigIdKey := fmt.Sprintf("%s%v", cacheSystemConfigIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, systemConfigConfigKeyKey, systemConfigIdKey)
	return err
}

func (m *defaultSystemConfigModel) FindOne(ctx context.Context, id int64) (*SystemConfig, error) {
	systemConfigIdKey := fmt.Sprintf("%s%v", cacheSystemConfigIdPrefix, id)
	var resp SystemConfig
	err := m.QueryRowCtx(ctx, &resp, systemConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemConfigModel) FindOneByConfigKey(ctx context.Context, configKey string) (*SystemConfig, error) {
	systemConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheSystemConfigConfigKeyPrefix, configKey)
	var resp SystemConfig
	err := m.QueryRowIndexCtx(ctx, &resp, systemConfigConfigKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `config_key` = ? limit 1", systemConfigRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, configKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemConfigModel) Insert(ctx context.Context, data *SystemConfig) (sql.Result, error) {
	systemConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheSystemConfigConfigKeyPrefix, data.ConfigKey)
	systemConfigIdKey := fmt.Sprintf("%s%v", cacheSystemConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, systemConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ConfigKey, data.ConfigValue, data.Remark)
	}, systemConfigConfigKeyKey, systemConfigIdKey)
	return ret, err
}

func (m *defaultSystemConfigModel) Update(ctx context.Context, newData *SystemConfig) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	systemConfigConfigKeyKey := fmt.Sprintf("%s%v", cacheSystemConfigConfigKeyPrefix, data.ConfigKey)
	systemConfigIdKey := fmt.Sprintf("%s%v", cacheSystemConfigIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ConfigKey, newData.ConfigValue, newData.Remark, newData.Id)
	}, systemConfigConfigKeyKey, systemConfigIdKey)
	return err
}

func (m *defaultSystemConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSystemConfigIdPrefix, primary)
}

func (m *defaultSystemConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSystemConfigModel) tableName() string {
	return m.table
}
