// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "server/internal/handler/admin"
	category "server/internal/handler/category"
	health "server/internal/handler/health"
	stat "server/internal/handler/stat"
	task "server/internal/handler/task"
	user "server/internal/handler/user"
	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// Security headers middleware for all API routes
	securityMw := serverCtx.SecurityHeadersMiddleware.Handle
	loginRateLimitMw := serverCtx.LoginRateLimitMiddleware.Handle

	// Health check — no auth, no middleware
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/health",
			Handler: health.HealthHandler(serverCtx),
		},
	})

	// Admin routes: protected by JWT + AdminMiddleware + OperationLogMiddleware
	adminRoutes := []rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/config",
			Handler: admin.ConfigListHandler(serverCtx),
		},
		{
			Method:  http.MethodPut,
			Path:    "/config",
			Handler: admin.UpdateConfigHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/log/login",
			Handler: admin.LoginLogListHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/log/operation",
			Handler: admin.OperationLogListHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/user",
			Handler: admin.UserListHandler(serverCtx),
		},
		{
			Method:  http.MethodDelete,
			Path:    "/user/:id",
			Handler: admin.DeleteUserHandler(serverCtx),
		},
		{
			Method:  http.MethodPut,
			Path:    "/user/:id/password",
			Handler: admin.ResetPasswordHandler(serverCtx),
		},
		{
			Method:  http.MethodPatch,
			Path:    "/user/:id/toggle",
			Handler: admin.ToggleUserStatusHandler(serverCtx),
		},
	}

	// Apply middlewares: security → operation log → admin
	adminRoutes = rest.WithMiddleware(securityMw, adminRoutes...)
	adminRoutes = rest.WithMiddleware(serverCtx.OperationLogMiddleware.Handle, adminRoutes...)
	adminRoutes = rest.WithMiddleware(serverCtx.AdminMiddleware.Handle, adminRoutes...)

	server.AddRoutes(
		adminRoutes,
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddleware(securityMw,
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/category",
					Handler: category.CategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/category",
					Handler: category.CreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/category/:id",
					Handler: category.UpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/category/:id",
					Handler: category.DeleteCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddleware(securityMw,
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stat",
					Handler: stat.StatHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddleware(securityMw,
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/task",
					Handler: task.CreateTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/task",
					Handler: task.TaskListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/task/:id",
					Handler: task.UpdateTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/task/:id",
					Handler: task.DeleteTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/task/:id",
					Handler: task.TaskDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/task/:id/toggle",
					Handler: task.ToggleTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/task/batch",
					Handler: task.BatchTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/task/trash",
					Handler: task.TrashListHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/task/:id/restore",
					Handler: task.RestoreTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/task/:id/permanent",
					Handler: task.PermanentDeleteTaskHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddleware(securityMw,
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/check-register",
					Handler: user.CheckRegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/register",
					Handler: user.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	// Login — with rate limiting
	server.AddRoutes(
		rest.WithMiddleware(loginRateLimitMw,
			rest.WithMiddleware(securityMw,
				[]rest.Route{
					{
						Method:  http.MethodPost,
						Path:    "/user/login",
						Handler: user.LoginHandler(serverCtx),
					},
				}...,
			)...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddleware(securityMw,
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
