// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BatchTaskReq struct {
	Ids    []int64 `json:"ids" validate:"required"`
	Action string  `json:"action" validate:"required" options:"complete|undo|delete"`
}

type BatchTaskResp struct {
}

type CategoryItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type CategoryListResp struct {
	List []CategoryItem `json:"list"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword" validate:"required"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=20"`
}

type ChangePasswordResp struct {
}

type CheckRegisterResp struct {
	AllowRegister bool `json:"allowRegister"`
}

type ConfigItem struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Remark string `json:"remark"`
}

type ConfigListResp struct {
	List []ConfigItem `json:"list"`
}

type CreateCategoryReq struct {
	Name string `json:"name" validate:"required,max=20"`
}

type CreateCategoryResp struct {
	Id int64 `json:"id"`
}

type CreateTaskReq struct {
	Title      string `json:"title" validate:"required,max=100"`
	Content    string `json:"content,optional" validate:"max=1000"`
	Priority   int64  `json:"priority,optional,default=2" options="1|2|3"`
	CategoryId int64  `json:"categoryId,optional"`
}

type CreateTaskResp struct {
	Id int64 `json:"id"`
}

type DeleteTaskReq struct {
	Id int64 `path:"id"`
}

type DeleteTaskResp struct {
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
}

type LoginLogItem struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	Username   string `json:"username"`
	Ip         string `json:"ip"`
	Status     int64  `json:"status"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
}

type LoginLogReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Username string `form:"username,optional"`
}

type LoginLogResp struct {
	Total int64          `json:"total"`
	List  []LoginLogItem `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token   string `json:"token"`
	IsAdmin int64  `json:"isAdmin"`
}

type OperationLogItem struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	TargetType string `json:"targetType"`
	TargetId   int64  `json:"targetId"`
	Detail     string `json:"detail"`
	Ip         string `json:"ip"`
	CreateTime string `json:"createTime"`
}

type OperationLogReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Action   string `form:"action,optional"`
	Username string `form:"username,optional"`
}

type OperationLogResp struct {
	Total int64              `json:"total"`
	List  []OperationLogItem `json:"list"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6,max=20"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type ResetPasswordReq struct {
	Id          int64  `path:"id"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=20"`
}

type ResetPasswordResp struct {
}

type StatResp struct {
	Total    int64 `json:"total"`
	Done     int64 `json:"done"`
	Todo     int64 `json:"todo"`
	DoneRate int64 `json:"doneRate"`
}

type TaskDetailReq struct {
	Id int64 `path:"id"`
}

type TaskDetailResp struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       int64  `json:"status"`
	Priority     int64  `json:"priority"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type TaskItem struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       int64  `json:"status"`
	Priority     int64  `json:"priority"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	CreateTime   string `json:"createTime"`
}

type TaskListReq struct {
	Page       int64  `form:"page,default=1"`
	PageSize   int64  `form:"pageSize,default=10"`
	Status     int64  `form:"status,optional" options="0|1"`
	CategoryId int64  `form:"categoryId,optional"`
	Priority   int64  `form:"priority,optional" options="1|2|3"`
	Keyword    string `form:"keyword,optional"`
}

type TaskListResp struct {
	Total int64      `json:"total"`
	List  []TaskItem `json:"list"`
}

type ToggleTaskReq struct {
	Id int64 `path:"id"`
}

type ToggleTaskResp struct {
}

type ToggleUserStatusReq struct {
	Id int64 `path:"id"`
}

type ToggleUserStatusResp struct {
}

type UpdateConfigReq struct {
	Key   string `json:"key" validate:"required"`
	Value string `json:"value" validate:"required"`
}

type UpdateConfigResp struct {
}

type UpdateTaskReq struct {
	Id         int64  `path:"id"`
	Title      string `json:"title,optional" validate:"max=100"`
	Content    string `json:"content,optional" validate:"max=1000"`
	Priority   int64  `json:"priority,optional" options="1|2|3"`
	CategoryId int64  `json:"categoryId,optional"`
}

type UpdateTaskResp struct {
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	IsAdmin  int64  `json:"isAdmin"`
	Status   int64  `json:"status"`
}

type UserListItem struct {
	Id         int64  `json:"id"`
	Username   string `json:"username"`
	IsAdmin    int64  `json:"isAdmin"`
	Status     int64  `json:"status"`
	CreateTime string `json:"createTime"`
}

type UserListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type UserListResp struct {
	Total int64          `json:"total"`
	List  []UserListItem `json:"list"`
}
