// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BatchTaskReq struct {
	Ids    []int64 `json:"ids"`
	Action string  `json:"action,options=complete|undo|delete|restore"`
}

type BatchTaskResp struct {
}

type SortTaskReq struct {
	Orders []SortOrderItem `json:"orders"`
}

type SortOrderItem struct {
	Id        int64 `json:"id"`
	SortOrder int64 `json:"sortOrder"`
}

type SortTaskResp struct {
}

type CategoryItem struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Color    string `json:"color"`
	Icon     string `json:"icon"`
	Sort     int64  `json:"sort"`
	IsSystem int64  `json:"isSystem"`
}

type CategoryListResp struct {
	List []CategoryItem `json:"list"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResp struct {
}

type CheckRegisterResp struct {
	AllowRegister bool `json:"allowRegister"`
}

type ConfigItem struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Remark string `json:"remark"`
}

type ConfigListResp struct {
	List []ConfigItem `json:"list"`
}

type CreateCategoryReq struct {
	Name  string `json:"name"`
	Color string `json:"color,optional"`
}

type CreateCategoryResp struct {
	Id int64 `json:"id"`
}

type UpdateCategoryReq struct {
	Id    int64   `path:"id"`
	Name  *string `json:"name,optional"`
	Color *string `json:"color,optional"`
	Icon  *string `json:"icon,optional"`
	Sort  *int64  `json:"sort,optional"`
}

type UpdateCategoryResp struct{}

type DeleteCategoryReq struct {
	Id int64 `path:"id"`
}

type DeleteCategoryResp struct{}

type CreateTaskReq struct {
	Title      string `json:"title"`
	Content    string `json:"content,optional"`
	Priority   int64  `json:"priority,optional,default=3,options=1|2|3"`
	CategoryId int64  `json:"categoryId,optional"`
	StartTime  string `json:"startTime,optional"`
	EndTime    string `json:"endTime,optional"`
	Reminder   string `json:"reminder,optional"`
	Tags       string `json:"tags,optional"`
}

type CreateTaskResp struct {
	Id int64 `json:"id"`
}

type ExportTaskReq struct {
	Format     string `form:"format,default=json,options=csv|json"`
	Status     int64  `form:"status,default=-1,options=-1|0|2"`
	CategoryId int64  `form:"categoryId,default=-1"`
	Priority   int64  `form:"priority,default=-1,options=-1|1|2|3"`
	Keyword    string `form:"keyword,optional"`
}

type DeleteTaskReq struct {
	Id int64 `path:"id"`
}

type DeleteTaskResp struct {
}

type TrashItem struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       int64  `json:"status"`
	Priority     int64  `json:"priority"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	StartTime    string `json:"startTime"`
	EndTime      string `json:"endTime"`
	Reminder     string `json:"reminder"`
	Tags         string `json:"tags"`
	SortOrder    int64  `json:"sortOrder"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type TrashListReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type TrashListResp struct {
	Total int64       `json:"total"`
	List  []TrashItem `json:"list"`
}

type RestoreTaskReq struct {
	Id int64 `path:"id"`
}

type RestoreTaskResp struct {
}

type PermanentDeleteTaskReq struct {
	Id int64 `path:"id"`
}

type PermanentDeleteTaskResp struct {
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
}

type LoginLogItem struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	Username   string `json:"username"`
	Ip         string `json:"ip"`
	Status     int64  `json:"status"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
}

type LoginLogReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Username string `form:"username,optional"`
}

type LoginLogResp struct {
	Total int64          `json:"total"`
	List  []LoginLogItem `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token   string `json:"token"`
	IsAdmin int64  `json:"isAdmin"`
}

type OperationLogItem struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	Username   string `json:"username"`
	Action     string `json:"action"`
	TargetType string `json:"targetType"`
	TargetId   int64  `json:"targetId"`
	Detail     string `json:"detail"`
	Ip         string `json:"ip"`
	CreateTime string `json:"createTime"`
}

type OperationLogReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Action   string `form:"action,optional"`
	Username string `form:"username,optional"`
}

type OperationLogResp struct {
	Total int64              `json:"total"`
	List  []OperationLogItem `json:"list"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type ResetPasswordReq struct {
	Id          int64  `path:"id"`
	NewPassword string `json:"newPassword"`
}

type ResetPasswordResp struct {
}

type StatResp struct {
	Total    int64 `json:"total"`
	Done     int64 `json:"done"`
	Todo     int64 `json:"todo"`
	DoneRate int64 `json:"doneRate"`
}

type TaskDetailReq struct {
	Id int64 `path:"id"`
}

type TaskDetailResp struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       int64  `json:"status"`
	Priority     int64  `json:"priority"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	StartTime    string `json:"startTime"`
	EndTime      string `json:"endTime"`
	Reminder     string `json:"reminder"`
	Tags         string `json:"tags"`
	SortOrder    int64  `json:"sortOrder"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type TaskItem struct {
	Id           int64  `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Status       int64  `json:"status"`
	Priority     int64  `json:"priority"`
	CategoryId   int64  `json:"categoryId"`
	CategoryName string `json:"categoryName"`
	StartTime    string `json:"startTime"`
	EndTime      string `json:"endTime"`
	Reminder     string `json:"reminder"`
	Tags         string `json:"tags"`
	SortOrder    int64  `json:"sortOrder"`
	CreateTime   string `json:"createTime"`
}

type TaskListReq struct {
	Page       int64  `form:"page,default=1"`
	PageSize   int64  `form:"pageSize,default=10"`
	Status     int64  `form:"status,default=-1,options=-1|0|2"`
	CategoryId int64  `form:"categoryId,default=-1"`
	Priority   int64  `form:"priority,default=-1,options=-1|1|2|3"`
	Keyword    string `form:"keyword,optional"`
}

type TaskListResp struct {
	Total int64      `json:"total"`
	List  []TaskItem `json:"list"`
}

type ToggleTaskReq struct {
	Id int64 `path:"id"`
}

type ToggleTaskResp struct {
}

type ToggleUserStatusReq struct {
	Id int64 `path:"id"`
}

type ToggleUserStatusResp struct {
}

type UpdateConfigReq struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UpdateConfigResp struct {
}

type UpdateTaskReq struct {
	Id         int64   `path:"id"`
	Title      *string `json:"title,optional"`
	Content    *string `json:"content,optional"`
	Priority   *int64  `json:"priority,optional,options=1|2|3"`
	CategoryId *int64  `json:"categoryId,optional"`
	StartTime  *string `json:"startTime,optional"`
	EndTime    *string `json:"endTime,optional"`
	Reminder   *string `json:"reminder,optional"`
	Tags       *string `json:"tags,optional"`
}

type UpdateTaskResp struct {
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	IsAdmin  int64  `json:"isAdmin"`
	Status   int64  `json:"status"`
}

type UserListItem struct {
	Id         int64  `json:"id"`
	Username   string `json:"username"`
	IsAdmin    int64  `json:"isAdmin"`
	Status     int64  `json:"status"`
	CreateTime string `json:"createTime"`
}

type UserListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
	Keyword  string `form:"keyword,optional"`
}

type UserListResp struct {
	Total int64          `json:"total"`
	List  []UserListItem `json:"list"`
}

type BackupItem struct {
	FileName  string `json:"fileName"`
	FileSize  int64  `json:"fileSize"`
	CreateTime string `json:"createTime"`
}

type BackupListResp struct {
	List []BackupItem `json:"list"`
}

type TagItem struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Color    string `json:"color"`
	IsSystem int64  `json:"isSystem"`
}

type TagListReq struct {
	Keyword string `form:"keyword,optional"`
}

type TagListResp struct {
	List []TagItem `json:"list"`
}

type CreateTagReq struct {
	Name  string `json:"name"`
	Color string `json:"color,optional"`
}

type CreateTagResp struct {
	Id int64 `json:"id"`
}

type UpdateTagReq struct {
	Id    int64   `path:"id"`
	Name  *string `json:"name,optional"`
	Color *string `json:"color,optional"`
}

type UpdateTagResp struct {
	Success bool `json:"success"`
}

type DeleteTagReq struct {
	Id int64 `path:"id"`
}

type DeleteTagResp struct {
	Success bool `json:"success"`
}

type TriggerBackupReq struct {
}

type TriggerBackupResp struct {
	FileName string `json:"fileName"`
	FileSize int64  `json:"fileSize"`
}

type DownloadBackupReq struct {
	FileName string `path:"fileName"`
}

type RestoreBackupReq struct {
	FileName string `path:"fileName"`
}

type RestoreBackupResp struct {
	PreRestoreBackup string `json:"preRestoreBackup"`
}
